Added fake Directories to file.go
jaswdr/faker pull request #111
Opened 2022-08-05 17:37 UTC by adrubesh

**Description**

This PR adds fake directories to file.go, including tests. 

**Are you trying to fix an existing issue?**

No

**Go Version**

```
$ go version
# replace this line with the output
```

**Go Tests**

```
➜  faker git:(file_directories) ✗ go test -v -run "TestDriveLetter|TestAbsolutePath|TestDirectory"
=== RUN   TestDirectory
--- PASS: TestDirectory (0.00s)
=== RUN   TestDriveLetter
--- PASS: TestDriveLetter (0.00s)
=== RUN   TestAbsolutePath
--- PASS: TestAbsolutePath (0.00s)
PASS
ok      github.com/jaswdr/faker 0.004s

➜  faker git:(file_directories) ✗ GOOS=windows go test -v -run "TestDriveLetter|TestAbsolutePath|TestDirectory"
=== RUN   TestDirectory
--- PASS: TestDirectory (0.00s)
=== RUN   TestDriveLetter
--- PASS: TestDriveLetter (0.00s)
=== RUN   TestAbsolutePath
--- PASS: TestAbsolutePath (0.00s)
PASS
ok      github.com/jaswdr/faker 0.166s

```

2022-08-05 20:49 UTC, jaswdr requested changes
Thank very much for your contribution. I left some comments, please take a look when possible.

2022-08-05 20:49 UTC, jaswdr commented on file.go
> +		return f.DriveLetter() + filepath.Join(f.Faker.Lorem().Words(nbLen)...)
Can you move this function to another file called `directory.go`?

Please implement this for Unix systems too, you can use the `os.PathSeparator` to generate random paths. Also, you need to create a test that covers these lines.

2022-08-05 20:49 UTC, jaswdr commented on file.go
> +	return filepath.Join(f.DriveLetter(), f.Directory(nbLen), f.FilenameWithExtension())
Can you rename the function to clarify that is a random path to a **file**, renaming it to `AbsoluteFilePathForWindows` and the previous one to `AbsoluteFilePathForUnix`. Please rename `nbLen` to `levels` to clarify that we are talking about how many deep levels the path will have.

One improvement suggestion is to create a `FilePath` function that calls each specific FilePath* function depending where the system is running. So you would have something like:

```go
func (f File) AbsoluteFilePath(levels int) string {
    if runtime.GOOS == "windows" {
        return AbsoluteFilePathForWindows(levels)
    }

    return AbsoluteFilePathForUnix(levels)
}
```

Please also create a test for this function.

2022-08-05 22:19 UTC, adrubesh commented
@jaswdr I made some of the changes you requested, and implemented some additional OS independent pathing. Here is some example output:

```
GOOS:  linux
====Fake Directories====
Directory(2):           /officiis/voluptatum
UnixDirectory(2):       /dolorum/et
WindowsDirectory(2):    x:\odio\accusamus
DriveLetter():          a:\
====Fake File Paths====
AbsoluteFilePath(2):            /nemo/expedita/impedit.csv
AbsoluteFilePathForUnix(2):     /molestias/aut/enim.m3u
AbsoluteFilePathForWindows(2):  e:\dolores\maiores\in.eot

GOOS:  windows
====Fake Directories====
Directory(2):           w:\libero\excepturi
UnixDirectory(2):       /id/rerum
WindowsDirectory(2):    n:\quos\aut
DriveLetter():          e:\
====Fake File Paths====
AbsoluteFilePath(2):            x:\in\est\rerum.pl
AbsoluteFilePathForUnix(2):     /eveniet/perspiciatis/ratione.ttf
AbsoluteFilePathForWindows(2):  s:\doloremque\voluptas\et.gif

```

2022-08-06 09:11 UTC, jaswdr requested changes

2022-08-06 09:11 UTC, jaswdr commented on directory.go
> +		prefix = d.DriveLetter()
You need to create a test that covers this line, you can create tests by not using the runtime.GOOS directly, but using an interface and mocking it. I did a similar think in [this](https://github.com/jaswdr/faker/blob/62506c31084e1a2fd33d67d578e1c22a07865c7d/utils.go#L14) file, where I create an interface that I used in [this](https://github.com/jaswdr/faker/blob/62506c31084e1a2fd33d67d578e1c22a07865c7d/lorem_flickr.go#L15) file and I mock it in [this](https://github.com/jaswdr/faker/blob/master/lorem_flickr_test.go#L39) test.

2022-08-06 09:11 UTC, jaswdr commented on file.go
> +func (f File) AbsoluteFilePath(levels int) string {
You can use the other two AbsoluteFilePathFor* methods here and avoid to duplicate the logic.

2022-08-06 14:30 UTC, adrubesh commented
@jaswdr I added the `OSResolver` interface to take care of that, wasn't sure if it needed to go it `utils.go`, `file.go` or `directory.go` but `utils.go` seemed like a good place for it. Let me know what you think.

2022-08-07 13:57 UTC, jaswdr approved these changes
LGTM, merging.

2022-08-07 13:58 UTC, merged

2022-08-07 14:00 UTC, jaswdr commented
Released in [v1.15.0](https://github.com/jaswdr/faker/releases/tag/v1.15.0), congratulations for your first contribution 🎉