feat: added Bitcoin address generation
jaswdr/faker pull request #86
Opened 2022-01-28 05:12 UTC by xlanor

**Description**

Added Bitcoin address generation based on discussion in #78 

**Are you trying to fix an existing issue?**

#78 

**Go Version**

```
abc@c63bccef3747:~/workspace/oss/faker$ go version
go version go1.17.3 linux/amd64
```

**Go Tests**

```
abc@c63bccef3747:~/workspace/oss/faker$ go test
PASS
ok      github.com/jaswdr/faker 5.644s
abc@c63bccef3747:~/workspace/oss/faker$ 
```

2022-01-31 22:05 UTC, jaswdr requested changes
@xlanor thanks for the PR, I have just some comments mostly related to comments and syntax, can you take a look when possible?

2022-01-31 22:05 UTC, jaswdr commented on crypto.go
> +// Helper function to return a bitcoin
just to confirm, by `return a bitcoin` you mean one bitcoin hash? if so, can you change this message to be clear that it is a bitcoin hash?

2022-02-02 06:38 UTC, xlanor commented
Changes made as reuqested!

2022-02-02 08:54 UTC, jaswdr approved these changes

2022-02-02 08:54 UTC, merged

2022-02-02 08:55 UTC, jaswdr commented
LGTM, merged 👍